# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-02 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mithril', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='cidr',
            field=models.PositiveSmallIntegerField(db_index=True, default=32),
        ),
        migrations.AlterField(
            model_name='range',
            name='ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='whitelist',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
